### ISSUE TITLE
Login / Register without filling in form fields crashes the app or just doesn't do anything

### ISSUE THREAD

**Issue by vherus** [boolean-uk/team-dev-client-c12#12]

**Comment by FullStackWebDeveloper-HARSH** [comment]
Hi Nathan,

I would like to work on this issue. Could you please assign it to me?
I request could you provide video of bug which is occurring that crashes app

Thank you!

Best regards,
Harsh.

**Comment by MyrtheDullaart** [comment]
When failing to fill in all fields of the register form, the user is still directed to the verification page.

To prevent this:
- The password and email fields should be required.
- The error should be handled

**Comment by PerikK** [comment]
-Controller must return proper error when trying to create a new user without  "email" OR "password"

/users POST:{
"email": "example@example.com"
}
should return an error if email OR password are missing and NOT crash the server

Response: status = 400
```json
{
  "status": "string",
       "data": {
         "error": "string"
   }
}
```

The response In case of succesfull user creation should be:

Response: status = 201

```json

{
"status": "success",
      "data": {
          "user": {
                "id": 0,
                "email": "string",
                "cohortId": 0,
                "role": "string",
                "firstName": "string",
                "lastName": "string",
                "bio": "string",
                "githubUrl": "string"
            }
      }
}
```

-Email and password must be checked for validity

-Check email string for valid email format
-Check password's validity (Must contain: > 8 characters, at least one uppercase letter, one number and one special character)
Checking validity must be added in the user controller.

If invalid inputs are detected an error should be returned

Response: status = 400
```json
{
 "status": "error",
    "data": {
        "error": "error message"
    }
}
```

-Update DB schema so that firstName and lastName are nullable.
