### ISSUE TITLE
Fix Logs endpoint to access the Database

### ISSUE THREAD

**Issue by angustownsley** [boolean-uk/team-dev-client-c12#20]
The endpoint is currently lacking a domain layer, so one will need to be created. Once the domain is created, the controller will need to be updated to use it. This controller will also need, 

Logs Endpoint:
/logs POST:

Request Body:
```json
{
  "date": "string",
  "cohortId": 0,
  "lines": [
    {
      "content": "string"
    }
  ]
}
```

Domain must return the newly created log's ID, cohortId, date, author, and all lines with their IDs and content.

Response
```json
{
  "status": "string",
  "data": {
    "log": {
      "id": 0,
      "cohortId": 0,
      "date": "string",
      "author": {
        "id": 0,
        "firstName": "string",
        "lastName": "string"
      },
      "lines": [
        {
          "id": 0,
          "content": "string"
        }
      ]
    }
  }
}
```

Error Response:

```json
{
  "status": "string",
  "data": {
    "error": "string"
  }
}
```

**Controllers**

Once the domain is created, the controller will need to be updated.

Ensure the controller has appropriate error handling

**Documentation**

Controller changes must be reflected in the documentation.

**Comment by PerikK** [comment]
This is almost done. But!
I had to make some changes to other parts of the codebase.

- Had to create a getCohortById function in cohort's domain, to be able to reference the cohort.
- Had to change the DeliveryLog model, so there is a default value for date. I'm not sure this is required, because in the designs the date referes to the duration of the course and not the date the Log is created.  
- I have trouble handling the errors in the controller.
